name: dart_koans
description: A sample command-line application.
version: 0.0.2
homepage: https://github.com/md-weber/dart_koans
author: Max Weber <flutterexp+github@gmail.com>

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.8.0
  watcher: ^1.0.0
  ansicolor: ^2.0.1

dev_dependencies:
  lints: ^1.0.1
  test: ^1.17.12
