name: dart_koans
description: A sample command-line application.
# version: 1.0.0
# homepage: https:///www.example.com
# author: myracledesign <weber.max.1988@live.de>

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  path: ^1.6.0
  watcher: ^0.9.7+15
  ansicolor: ^1.0.2

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.3
